### ISSUE TITLE
CI/CD 구축하기

### ISSUE THREAD

**Issue by pjh5365** [KakaoTech-BootCamp-Team-2/Kaboo-Chat#3]
### TODO
- [x]  도커 파일 작성
- [x]  도커 컴포즈 파일 작성
- [x]  Github Action 추가
- [x]  EC2 연결
- [x]  트리거 감지, 자동 배포

**Comment by pjh5365** [comment]
Squash And Merge 완료 👍
